"""empty message

Revision ID: 5a19f00038f5
Revises: dd88a2656fb2
Create Date: 2018-06-02 18:25:51.109465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a19f00038f5'
down_revision = 'dd88a2656fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_time')
    # ### end Alembic commands ###
