"""empty message

Revision ID: 60c65d53ca2f
Revises: 7475f1dc7dfc
Create Date: 2018-06-01 23:57:33.703278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60c65d53ca2f'
down_revision = '7475f1dc7dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_s', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'password_s')
    # ### end Alembic commands ###
