"""empty message

Revision ID: 7475f1dc7dfc
Revises: 
Create Date: 2018-06-01 23:00:02.423118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7475f1dc7dfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mps',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('nick_name', sa.String(length=60), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_index(op.f('ix_mps_nick_name'), 'mps', ['nick_name'], unique=False)
    op.create_table('roles',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_groups',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('nick_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_index(op.f('ix_user_groups_nick_name'), 'user_groups', ['nick_name'], unique=False)
    op.create_index(op.f('ix_user_groups_owner_id'), 'user_groups', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.SmallInteger(), nullable=True),
    sa.Column('nick_name', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=63), nullable=True),
    sa.Column('current_login_ip', sa.String(length=63), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_index(op.f('ix_users_nick_name'), 'users', ['nick_name'], unique=False)
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    mysql_charset='utf8mb4'
    )
    op.create_table('group_relationship',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    mysql_charset='utf8mb4'
    )
    op.create_table('mp_relationship',
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    mysql_charset='utf8mb4'
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('mp_relationship')
    op.drop_table('group_relationship')
    op.drop_table('friends')
    op.drop_index(op.f('ix_users_nick_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_groups_owner_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_nick_name'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_table('roles')
    op.drop_index(op.f('ix_mps_nick_name'), table_name='mps')
    op.drop_table('mps')
    # ### end Alembic commands ###
