"""empty message

Revision ID: dd88a2656fb2
Revises: 60c65d53ca2f
Create Date: 2018-06-01 23:58:07.263075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd88a2656fb2'
down_revision = '60c65d53ca2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_s')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_s', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
